### PR TITLE
Add optional onClick parameter

### PR DESCRIPTION
**Pull request by CarlosEsco**
this allows clicking lists, paragraphs (anything using markdownText)

### CODE REVIEW

**Comment by mikepenz** [comment]
Given that it will apply to the whole markdown, how would this differ than setting a click listener to the whole composable itself?

**Comment by mikepenz** [comment]
The modified would be passed onto this `Column` spanning around the whole content: https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/src/commonMain/kotlin/com/mikepenz/markdown/Markdown.kt#L68 
Which I'd expect to handle the listener 🤔  is it consumed by something else?

**Comment by CarlosEsco** [comment]
As far as I remember when I tried that. It makes the column clickable, but that only allows clicking on the empty spaces so clicking a paragraph is ignored because the touch events are being consumed on the markdown stuff

**Comment by mikepenz** [comment]
Added a partial solution by not attaching the touch handling for urls if there is no url. 

I understand that this currently would still not work if there is a URL within the specific paragraph, but I'd prefer to have a better handling for those cases to not consume the touch 🤔 

couldn't find a proper solution with the available APIs not sure if it may just not be possible at this time

**Pull request closed without merging**
